resources:
- name: git
  type: git
  source:
    branch: master
    uri: https://github.com/jpw/trop-app.git

- name: git-docs
  type: git
  source:
    branch: master
    uri: https://github.com/jpw/trop-docs.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: user
    password: pass
    organization: pcfdev-org
    space: pcfdev-space
    skip-cert-check: true

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: git
      trigger: true
    - get: git-docs
      trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: dubnium-slim
      run:
        path: /bin/sh
        args:
        - -c
        - |-

          export GIT_REVISION=`cat .git/ref`

          ./build.sh
          EXIT_STATUS=$?
          if [ $EXIT_STATUS != 0 ] ; then
            exit 1
          fi

        dir: git
      inputs:
      - name: git
      - name: git-docs
      outputs:
      - name: built

- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: built
  - put: resource-deploy-web-app
    params:
      manifest: trop-app/manifest.yml
      environment_variables:
        SOME_KEY1: value
        SOME_KEY2: value2