resources:
- name: git
  type: git
  source:
    branch: master
    uri: https://github.com/jpw/trop-app.git
jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: git
      trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: dubnium-slim
      run:
        path: /bin/sh
        args:
        - -c
        - |-

          export GIT_REVISION=`cat .git/ref`

          ./build.sh
          EXIT_STATUS=$?
          if [ $EXIT_STATUS != 0 ] ; then
            exit 1
          fi

        dir: git
      inputs:
      - name: git